### Ecuaciones Diferenciales

In [1]:
import math as m
import numpy as np
import matplotlib.pyplot as plt

Manejo de matrices/vectores

In [2]:
x = np.array([2,5])
y = np.array([4,9])
x, y, x*y, np.dot(x,y)

(array([2, 5]), array([4, 9]), array([ 8, 45]), 53)

In [3]:
M = np.array([[3,5],[7,2]])
M, np.dot(M,x)

(array([[3, 5],
        [7, 2]]),
 array([31, 24]))

In [4]:
np.transpose(M), np.trace(M), np.linalg.det(M)

(array([[3, 7],
        [5, 2]]),
 5,
 -29.000000000000004)

Tenemos un sistema de ecuaciones diferenciales ordinarias

$$
\frac{d\vec{x}}{dt} = \vec{g}(\vec{x},t)
$$
$$
\vec x_{n+1} = \vec{x}_n +\delta\vec{g}(\vec{x}_n,t_n) +\frac{\delta{^2}}{2}\mathbb{J}(\vec{x}_n,t_n)\cdot\vec{g}(\vec{x}_n,t_n)
$$

donde $\delta$ es el paso de integración y $\vec{x}$ son las variables del sistema de ecuaciones diferenciales.

In [5]:
def pendulo_simple(x , w2=1):
    # x = (theta, v_theta)
    return np.array([ x[1] , -w2*np.sin(x[0]) ])

def EDO_Euler(g,x0,t,h=0.1):
    N = int((t[1]-t[0])/h)
    tiempo = np.linspace(t[0],t[1],N)
    sol = np.zeros((len(x0),N))
    sol[:,0] = x0
    for i in range(N-1):
        sol[:,i+1] = sol[:,i] + h*g(sol[:,i])
    return sol

In [6]:
EDO_Euler(pendulo_simple,[1,0],[0,np.pi])

array([[ 1.        ,  1.        ,  0.99158529,  0.97475587,  0.9495575 ,
         0.91608349,  0.87447789,  0.82494007,  0.76773015,  0.70317517,
         0.63167515,  0.5537087 ,  0.46983727,  0.38070739,  0.2870501 ,
         0.18967703,  0.08947273, -0.012617  , -0.11560026, -0.21845735,
        -0.32016101, -0.41969744, -0.51608667, -0.60840105, -0.69578064,
        -0.77744466, -0.85269884, -0.92093841, -0.98164739, -1.03439468,
        -1.07882782],
       [ 0.        , -0.0841471 , -0.1682942 , -0.25198367, -0.33474016,
        -0.41605596, -0.49537824, -0.57209912, -0.64554983, -0.71500022,
        -0.77966451, -0.83871426, -0.8912988 , -0.93657292, -0.97373065,
        -1.00204308, -1.02089725, -1.02983259, -1.02857092, -1.01703663,
        -0.99536424, -0.9638923 , -0.92314388, -0.87379586, -0.81664024,
        -0.75254176, -0.68239571, -0.60708982, -0.52747284, -0.44433146,
        -0.35837614]])

Fricción numérica