### Ecuaciones Diferenciales

In [1]:
import math as m
import numpy as np
import matplotlib.pyplot as plt

Manejo de matrices/vectores

In [2]:
x = np.array([2,5])
y = np.array([4,9])
x, y, x*y, np.dot(x,y)

(array([2, 5]), array([4, 9]), array([ 8, 45]), 53)

In [4]:
M = np.array([[3,5],[7,2]])
M, np.dot(M,x)

(array([[3, 5],
        [7, 2]]),
 array([31, 24]))

In [6]:
np.transpose(M), np.trace(M), np.linalg.det(M)

(array([[3, 7],
        [5, 2]]),
 5,
 -29.000000000000004)

In [7]:
M

array([[3, 5],
       [7, 2]])